// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubresource

import (
	"context"
	"net/url"

	"github.com/Khan/genqlient/graphql"
)

// The possible states of a pull request.
type PullRequestState string

const (
	// A pull request that has been closed without being merged.
	PullRequestStateClosed PullRequestState = "CLOSED"
	// A pull request that has been closed by being merged.
	PullRequestStateMerged PullRequestState = "MERGED"
	// A pull request that is still open.
	PullRequestStateOpen PullRequestState = "OPEN"
)

var AllPullRequestState = []PullRequestState{
	PullRequestStateClosed,
	PullRequestStateMerged,
	PullRequestStateOpen,
}

// __getPullRequestsInput is used internally by genqlient
type __getPullRequestsInput struct {
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	States    []PullRequestState `json:"states"`
	Labels    []string           `json:"labels"`
	EndCursor string             `json:"endCursor"`
}

// GetOwner returns __getPullRequestsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetOwner() string { return v.Owner }

// GetName returns __getPullRequestsInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetName() string { return v.Name }

// GetStates returns __getPullRequestsInput.States, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetStates() []PullRequestState { return v.States }

// GetLabels returns __getPullRequestsInput.Labels, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetLabels() []string { return v.Labels }

// GetEndCursor returns __getPullRequestsInput.EndCursor, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetEndCursor() string { return v.EndCursor }

// getPullRequestsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestsRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestsRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestsRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepository) GetPullRequests() getPullRequestsRepositoryPullRequestsPullRequestConnection {
	return v.PullRequests
}

// getPullRequestsRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type getPullRequestsRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getPullRequestsRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetNodes() []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest {
	return v.Nodes
}

// GetPageInfo returns getPullRequestsRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetPageInfo() getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo {
	return v.PageInfo
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest struct {
	// Identifies the pull request number.
	Number int `json:"number"`
	// Identifies if the pull request is a draft.
	IsDraft bool `json:"isDraft"`
	// The permalink to the pull request.
	Permalink url.URL `json:"permalink"`
	// Identifies the name of the base Ref associated with the pull request, even if the ref has been deleted.
	BaseRefName string `json:"baseRefName"`
}

// GetNumber returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.Number, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetNumber() int {
	return v.Number
}

// GetIsDraft returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.IsDraft, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetIsDraft() bool {
	return v.IsDraft
}

// GetPermalink returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.Permalink, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetPermalink() url.URL {
	return v.Permalink
}

// GetBaseRefName returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.BaseRefName, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetBaseRefName() string {
	return v.BaseRefName
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// GetHasNextPage returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// getPullRequestsResponse is returned by getPullRequests on success.
type getPullRequestsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestsRepository `json:"repository"`
}

// GetRepository returns getPullRequestsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestsResponse) GetRepository() getPullRequestsRepository { return v.Repository }

// The query executed by getPullRequests.
const getPullRequests_Operation = `
query getPullRequests ($owner: String!, $name: String!, $states: [PullRequestState!], $labels: [String!], $endCursor: String) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 100, after: $endCursor, states: $states, labels: $labels, orderBy: {field:CREATED_AT,direction:ASC}) {
			nodes {
				number
				isDraft
				permalink
				baseRefName
			}
			pageInfo {
				endCursor
				hasNextPage
			}
		}
	}
}
`

func getPullRequests(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	name string,
	states []PullRequestState,
	labels []string,
	endCursor string,
) (data_ *getPullRequestsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getPullRequests",
		Query:  getPullRequests_Operation,
		Variables: &__getPullRequestsInput{
			Owner:     owner,
			Name:      name,
			States:    states,
			Labels:    labels,
			EndCursor: endCursor,
		},
	}

	data_ = &getPullRequestsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
