// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubresource

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// The possible states of a pull request.
type PullRequestState string

const (
	// A pull request that has been closed without being merged.
	PullRequestStateClosed PullRequestState = "CLOSED"
	// A pull request that has been closed by being merged.
	PullRequestStateMerged PullRequestState = "MERGED"
	// A pull request that is still open.
	PullRequestStateOpen PullRequestState = "OPEN"
)

var AllPullRequestState = []PullRequestState{
	PullRequestStateClosed,
	PullRequestStateMerged,
	PullRequestStateOpen,
}

// __getPullRequestsInput is used internally by genqlient
type __getPullRequestsInput struct {
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	States    []PullRequestState `json:"states"`
	Labels    []string           `json:"labels"`
	EndCursor string             `json:"endCursor"`
}

// GetOwner returns __getPullRequestsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetOwner() string { return v.Owner }

// GetName returns __getPullRequestsInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetName() string { return v.Name }

// GetStates returns __getPullRequestsInput.States, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetStates() []PullRequestState { return v.States }

// GetLabels returns __getPullRequestsInput.Labels, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetLabels() []string { return v.Labels }

// GetEndCursor returns __getPullRequestsInput.EndCursor, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetEndCursor() string { return v.EndCursor }

// __latestCommitForPrInput is used internally by genqlient
type __latestCommitForPrInput struct {
	Owner  string `json:"owner"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

// GetOwner returns __latestCommitForPrInput.Owner, and is useful for accessing the field via an interface.
func (v *__latestCommitForPrInput) GetOwner() string { return v.Owner }

// GetName returns __latestCommitForPrInput.Name, and is useful for accessing the field via an interface.
func (v *__latestCommitForPrInput) GetName() string { return v.Name }

// GetNumber returns __latestCommitForPrInput.Number, and is useful for accessing the field via an interface.
func (v *__latestCommitForPrInput) GetNumber() int { return v.Number }

// getPullRequestsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestsRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestsRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestsRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepository) GetPullRequests() getPullRequestsRepositoryPullRequestsPullRequestConnection {
	return v.PullRequests
}

// getPullRequestsRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type getPullRequestsRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getPullRequestsRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetNodes() []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest {
	return v.Nodes
}

// GetPageInfo returns getPullRequestsRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetPageInfo() getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo {
	return v.PageInfo
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest struct {
	// Identifies the pull request number.
	Number int `json:"number"`
	// Identifies if the pull request is a draft.
	IsDraft bool `json:"isDraft"`
	// The permalink to the pull request.
	Permalink string `json:"permalink"`
	// Identifies the name of the base Ref associated with the pull request, even if the ref has been deleted.
	BaseRefName string `json:"baseRefName"`
}

// GetNumber returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.Number, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetNumber() int {
	return v.Number
}

// GetIsDraft returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.IsDraft, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetIsDraft() bool {
	return v.IsDraft
}

// GetPermalink returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.Permalink, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetPermalink() string {
	return v.Permalink
}

// GetBaseRefName returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.BaseRefName, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetBaseRefName() string {
	return v.BaseRefName
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// GetHasNextPage returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// getPullRequestsResponse is returned by getPullRequests on success.
type getPullRequestsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestsRepository `json:"repository"`
}

// GetRepository returns getPullRequestsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestsResponse) GetRepository() getPullRequestsRepository { return v.Repository }

// latestCommitForPrRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type latestCommitForPrRepository struct {
	// Returns a single pull request from the current repository by number.
	PullRequest latestCommitForPrRepositoryPullRequest `json:"pullRequest"`
}

// GetPullRequest returns latestCommitForPrRepository.PullRequest, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepository) GetPullRequest() latestCommitForPrRepositoryPullRequest {
	return v.PullRequest
}

// latestCommitForPrRepositoryPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type latestCommitForPrRepositoryPullRequest struct {
	// Identifies the name of the base Ref associated with the pull request, even if the ref has been deleted.
	BaseRefName string `json:"baseRefName"`
	// The permalink to the pull request.
	Permalink string `json:"permalink"`
	// A list of commits present in this pull request's head branch not present in the base branch.
	Commits latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection `json:"commits"`
}

// GetBaseRefName returns latestCommitForPrRepositoryPullRequest.BaseRefName, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequest) GetBaseRefName() string { return v.BaseRefName }

// GetPermalink returns latestCommitForPrRepositoryPullRequest.Permalink, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequest) GetPermalink() string { return v.Permalink }

// GetCommits returns latestCommitForPrRepositoryPullRequest.Commits, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequest) GetCommits() latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection {
	return v.Commits
}

// latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection includes the requested fields of the GraphQL type PullRequestCommitConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequestCommit.
type latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection struct {
	// A list of nodes.
	Nodes []latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit `json:"nodes"`
}

// GetNodes returns latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection.Nodes, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnection) GetNodes() []latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit {
	return v.Nodes
}

// latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit includes the requested fields of the GraphQL type PullRequestCommit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit part of a pull request.
type latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit struct {
	// The Git commit object
	Commit latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit `json:"commit"`
}

// GetCommit returns latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit.Commit, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommit) GetCommit() latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit {
	return v.Commit
}

// latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit struct {
	// The Git object ID
	Oid string `json:"oid"`
}

// GetOid returns latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit.Oid, and is useful for accessing the field via an interface.
func (v *latestCommitForPrRepositoryPullRequestCommitsPullRequestCommitConnectionNodesPullRequestCommitCommit) GetOid() string {
	return v.Oid
}

// latestCommitForPrResponse is returned by latestCommitForPr on success.
type latestCommitForPrResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository latestCommitForPrRepository `json:"repository"`
}

// GetRepository returns latestCommitForPrResponse.Repository, and is useful for accessing the field via an interface.
func (v *latestCommitForPrResponse) GetRepository() latestCommitForPrRepository { return v.Repository }

// The query executed by getPullRequests.
const getPullRequests_Operation = `
query getPullRequests ($owner: String!, $name: String!, $states: [PullRequestState!], $labels: [String!], $endCursor: String) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 100, after: $endCursor, states: $states, labels: $labels, orderBy: {field:CREATED_AT,direction:ASC}) {
			nodes {
				number
				isDraft
				permalink
				baseRefName
			}
			pageInfo {
				endCursor
				hasNextPage
			}
		}
	}
}
`

func getPullRequests(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	name string,
	states []PullRequestState,
	labels []string,
	endCursor string,
) (data_ *getPullRequestsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getPullRequests",
		Query:  getPullRequests_Operation,
		Variables: &__getPullRequestsInput{
			Owner:     owner,
			Name:      name,
			States:    states,
			Labels:    labels,
			EndCursor: endCursor,
		},
	}

	data_ = &getPullRequestsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by latestCommitForPr.
const latestCommitForPr_Operation = `
query latestCommitForPr ($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			baseRefName
			permalink
			commits(last: 1) {
				nodes {
					commit {
						oid
					}
				}
			}
		}
	}
}
`

func latestCommitForPr(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	name string,
	number int,
) (data_ *latestCommitForPrResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "latestCommitForPr",
		Query:  latestCommitForPr_Operation,
		Variables: &__latestCommitForPrInput{
			Owner:  owner,
			Name:   name,
			Number: number,
		},
	}

	data_ = &latestCommitForPrResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
