// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubresource

import (
	"context"
	"net/url"

	"github.com/Khan/genqlient/graphql"
)

// The possible states of a pull request.
type PullRequestState string

const (
	// A pull request that has been closed without being merged.
	PullRequestStateClosed PullRequestState = "CLOSED"
	// A pull request that has been closed by being merged.
	PullRequestStateMerged PullRequestState = "MERGED"
	// A pull request that is still open.
	PullRequestStateOpen PullRequestState = "OPEN"
)

var AllPullRequestState = []PullRequestState{
	PullRequestStateClosed,
	PullRequestStateMerged,
	PullRequestStateOpen,
}

// The repository's visibility level.
type RepositoryVisibility string

const (
	// The repository is visible only to users in the same enterprise.
	RepositoryVisibilityInternal RepositoryVisibility = "INTERNAL"
	// The repository is visible only to those with explicit access.
	RepositoryVisibilityPrivate RepositoryVisibility = "PRIVATE"
	// The repository is visible to everyone.
	RepositoryVisibilityPublic RepositoryVisibility = "PUBLIC"
)

var AllRepositoryVisibility = []RepositoryVisibility{
	RepositoryVisibilityInternal,
	RepositoryVisibilityPrivate,
	RepositoryVisibilityPublic,
}

// __getPullRequestsInput is used internally by genqlient
type __getPullRequestsInput struct {
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	States    []PullRequestState `json:"states"`
	Labels    []string           `json:"labels"`
	EndCursor string             `json:"endCursor"`
}

// GetOwner returns __getPullRequestsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetOwner() string { return v.Owner }

// GetName returns __getPullRequestsInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetName() string { return v.Name }

// GetStates returns __getPullRequestsInput.States, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetStates() []PullRequestState { return v.States }

// GetLabels returns __getPullRequestsInput.Labels, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetLabels() []string { return v.Labels }

// GetEndCursor returns __getPullRequestsInput.EndCursor, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetEndCursor() string { return v.EndCursor }

// __getRepositoriesInput is used internally by genqlient
type __getRepositoriesInput struct {
	Owner      string               `json:"owner"`
	IsUser     bool                 `json:"isUser"`
	IsOrg      bool                 `json:"isOrg"`
	IsFork     bool                 `json:"isFork"`
	IsArchived bool                 `json:"isArchived"`
	Visibility RepositoryVisibility `json:"visibility"`
	Cursor     string               `json:"cursor"`
}

// GetOwner returns __getRepositoriesInput.Owner, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetOwner() string { return v.Owner }

// GetIsUser returns __getRepositoriesInput.IsUser, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetIsUser() bool { return v.IsUser }

// GetIsOrg returns __getRepositoriesInput.IsOrg, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetIsOrg() bool { return v.IsOrg }

// GetIsFork returns __getRepositoriesInput.IsFork, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetIsFork() bool { return v.IsFork }

// GetIsArchived returns __getRepositoriesInput.IsArchived, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetIsArchived() bool { return v.IsArchived }

// GetVisibility returns __getRepositoriesInput.Visibility, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetVisibility() RepositoryVisibility { return v.Visibility }

// GetCursor returns __getRepositoriesInput.Cursor, and is useful for accessing the field via an interface.
func (v *__getRepositoriesInput) GetCursor() string { return v.Cursor }

// getPullRequestsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestsRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestsRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestsRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepository) GetPullRequests() getPullRequestsRepositoryPullRequestsPullRequestConnection {
	return v.PullRequests
}

// getPullRequestsRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type getPullRequestsRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getPullRequestsRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetNodes() []getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest {
	return v.Nodes
}

// GetPageInfo returns getPullRequestsRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnection) GetPageInfo() getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo {
	return v.PageInfo
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest struct {
	// Identifies the pull request number.
	Number int `json:"number"`
}

// GetNumber returns getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest.Number, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionNodesPullRequest) GetNumber() int {
	return v.Number
}

// getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// GetHasNextPage returns getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// getPullRequestsResponse is returned by getPullRequests on success.
type getPullRequestsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestsRepository `json:"repository"`
}

// GetRepository returns getPullRequestsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestsResponse) GetRepository() getPullRequestsRepository { return v.Repository }

// getRepositoriesOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An account on GitHub, with one or more owners, that has repositories, members and teams.
type getRepositoriesOrganization struct {
	// A list of repositories that the user owns.
	Repositories getRepositoriesOrganizationRepositoriesRepositoryConnection `json:"repositories"`
}

// GetRepositories returns getRepositoriesOrganization.Repositories, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganization) GetRepositories() getRepositoriesOrganizationRepositoriesRepositoryConnection {
	return v.Repositories
}

// getRepositoriesOrganizationRepositoriesRepositoryConnection includes the requested fields of the GraphQL type RepositoryConnection.
// The GraphQL type's documentation follows.
//
// A list of repositories owned by the subject.
type getRepositoriesOrganizationRepositoriesRepositoryConnection struct {
	// Information to aid in pagination.
	PageInfo getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo `json:"pageInfo"`
	// A list of nodes.
	Nodes []getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository `json:"nodes"`
}

// GetPageInfo returns getRepositoriesOrganizationRepositoriesRepositoryConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnection) GetPageInfo() getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo {
	return v.PageInfo
}

// GetNodes returns getRepositoriesOrganizationRepositoriesRepositoryConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnection) GetNodes() []getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository {
	return v.Nodes
}

// getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository struct {
	// The name of the repository.
	Name string `json:"name"`
	// The HTTP URL for this repository
	Url url.URL `json:"url"`
}

// GetName returns getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository.Name, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository) GetName() string {
	return v.Name
}

// GetUrl returns getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository.Url, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnectionNodesRepository) GetUrl() url.URL {
	return v.Url
}

// getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getRepositoriesOrganizationRepositoriesRepositoryConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// getRepositoriesResponse is returned by getRepositories on success.
type getRepositoriesResponse struct {
	// Lookup a organization by login.
	Organization getRepositoriesOrganization `json:"organization"`
	// Lookup a user by login.
	User getRepositoriesUser `json:"user"`
}

// GetOrganization returns getRepositoriesResponse.Organization, and is useful for accessing the field via an interface.
func (v *getRepositoriesResponse) GetOrganization() getRepositoriesOrganization {
	return v.Organization
}

// GetUser returns getRepositoriesResponse.User, and is useful for accessing the field via an interface.
func (v *getRepositoriesResponse) GetUser() getRepositoriesUser { return v.User }

// getRepositoriesUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getRepositoriesUser struct {
	// A list of repositories that the user owns.
	Repositories getRepositoriesUserRepositoriesRepositoryConnection `json:"repositories"`
}

// GetRepositories returns getRepositoriesUser.Repositories, and is useful for accessing the field via an interface.
func (v *getRepositoriesUser) GetRepositories() getRepositoriesUserRepositoriesRepositoryConnection {
	return v.Repositories
}

// getRepositoriesUserRepositoriesRepositoryConnection includes the requested fields of the GraphQL type RepositoryConnection.
// The GraphQL type's documentation follows.
//
// A list of repositories owned by the subject.
type getRepositoriesUserRepositoriesRepositoryConnection struct {
	// Information to aid in pagination.
	PageInfo getRepositoriesUserRepositoriesRepositoryConnectionPageInfo `json:"pageInfo"`
	// A list of nodes.
	Nodes []getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository `json:"nodes"`
}

// GetPageInfo returns getRepositoriesUserRepositoriesRepositoryConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnection) GetPageInfo() getRepositoriesUserRepositoriesRepositoryConnectionPageInfo {
	return v.PageInfo
}

// GetNodes returns getRepositoriesUserRepositoriesRepositoryConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnection) GetNodes() []getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository {
	return v.Nodes
}

// getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository struct {
	// The name of the repository.
	Name string `json:"name"`
	// The HTTP URL for this repository
	Url url.URL `json:"url"`
}

// GetName returns getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository.Name, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository) GetName() string {
	return v.Name
}

// GetUrl returns getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository.Url, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnectionNodesRepository) GetUrl() url.URL {
	return v.Url
}

// getRepositoriesUserRepositoriesRepositoryConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getRepositoriesUserRepositoriesRepositoryConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getRepositoriesUserRepositoriesRepositoryConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns getRepositoriesUserRepositoriesRepositoryConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getRepositoriesUserRepositoriesRepositoryConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// The query executed by getPullRequests.
const getPullRequests_Operation = `
query getPullRequests ($owner: String!, $name: String!, $states: [PullRequestState!], $labels: [String!], $endCursor: String) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 100, after: $endCursor, states: $states, labels: $labels, orderBy: {field:CREATED_AT,direction:ASC}) {
			nodes {
				number
			}
			pageInfo {
				endCursor
				hasNextPage
			}
		}
	}
}
`

func getPullRequests(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	name string,
	states []PullRequestState,
	labels []string,
	endCursor string,
) (data_ *getPullRequestsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getPullRequests",
		Query:  getPullRequests_Operation,
		Variables: &__getPullRequestsInput{
			Owner:     owner,
			Name:      name,
			States:    states,
			Labels:    labels,
			EndCursor: endCursor,
		},
	}

	data_ = &getPullRequestsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getRepositories.
const getRepositories_Operation = `
query getRepositories ($owner: String!, $isUser: Boolean!, $isOrg: Boolean!, $isFork: Boolean!, $isArchived: Boolean!, $visibility: RepositoryVisibility!, $cursor: String) {
	organization(login: $owner) @include(if: $isOrg) {
		repositories(first: 100, after: $cursor, isFork: $isFork, isArchived: $isArchived, visibility: $visibility, orderBy: {field:NAME,direction:ASC}) {
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				name
				url
			}
		}
	}
	user(login: $owner) @include(if: $isUser) {
		repositories(first: 100, after: $cursor, isFork: $isFork, isArchived: $isArchived, visibility: $visibility, orderBy: {field:NAME,direction:ASC}) {
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				name
				url
			}
		}
	}
}
`

func getRepositories(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	isUser bool,
	isOrg bool,
	isFork bool,
	isArchived bool,
	visibility RepositoryVisibility,
	cursor string,
) (data_ *getRepositoriesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getRepositories",
		Query:  getRepositories_Operation,
		Variables: &__getRepositoriesInput{
			Owner:      owner,
			IsUser:     isUser,
			IsOrg:      isOrg,
			IsFork:     isFork,
			IsArchived: isArchived,
			Visibility: visibility,
			Cursor:     cursor,
		},
	}

	data_ = &getRepositoriesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
