// Code generated by counterfeiter. DO NOT EDIT.
package githubresourcefakes

import (
	"sync"

	githubresource "github.com/PixelAirIO/github-resource"
)

type FakeGithubClient struct {
	APIEndpointsStub        func() (string, string)
	aPIEndpointsMutex       sync.RWMutex
	aPIEndpointsArgsForCall []struct {
	}
	aPIEndpointsReturns struct {
		result1 string
		result2 string
	}
	aPIEndpointsReturnsOnCall map[int]struct {
		result1 string
		result2 string
	}
	AccessTokenStub        func() string
	accessTokenMutex       sync.RWMutex
	accessTokenArgsForCall []struct {
	}
	accessTokenReturns struct {
		result1 string
	}
	accessTokenReturnsOnCall map[int]struct {
		result1 string
	}
	CheckoutPrStub        func(string, string, bool) error
	checkoutPrMutex       sync.RWMutex
	checkoutPrArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 bool
	}
	checkoutPrReturns struct {
		result1 error
	}
	checkoutPrReturnsOnCall map[int]struct {
		result1 error
	}
	FetchPrStub        func(string, string, int, bool, bool) error
	fetchPrMutex       sync.RWMutex
	fetchPrArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 int
		arg4 bool
		arg5 bool
	}
	fetchPrReturns struct {
		result1 error
	}
	fetchPrReturnsOnCall map[int]struct {
		result1 error
	}
	GetPRInfoStub        func(int) (githubresource.PullRequest, error)
	getPRInfoMutex       sync.RWMutex
	getPRInfoArgsForCall []struct {
		arg1 int
	}
	getPRInfoReturns struct {
		result1 githubresource.PullRequest
		result2 error
	}
	getPRInfoReturnsOnCall map[int]struct {
		result1 githubresource.PullRequest
		result2 error
	}
	HostEndpointStub        func() string
	hostEndpointMutex       sync.RWMutex
	hostEndpointArgsForCall []struct {
	}
	hostEndpointReturns struct {
		result1 string
	}
	hostEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	InitRepoStub        func(string, string) error
	initRepoMutex       sync.RWMutex
	initRepoArgsForCall []struct {
		arg1 string
		arg2 string
	}
	initRepoReturns struct {
		result1 error
	}
	initRepoReturnsOnCall map[int]struct {
		result1 error
	}
	LatestCommitForPRStub        func(int) (string, error)
	latestCommitForPRMutex       sync.RWMutex
	latestCommitForPRArgsForCall []struct {
		arg1 int
	}
	latestCommitForPRReturns struct {
		result1 string
		result2 error
	}
	latestCommitForPRReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ListPullRequestsStub        func([]githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)
	listPullRequestsMutex       sync.RWMutex
	listPullRequestsArgsForCall []struct {
		arg1 []githubresource.PullRequestState
		arg2 []string
	}
	listPullRequestsReturns struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	listPullRequestsReturnsOnCall map[int]struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	MergePrStub        func(string, bool) error
	mergePrMutex       sync.RWMutex
	mergePrArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	mergePrReturns struct {
		result1 error
	}
	mergePrReturnsOnCall map[int]struct {
		result1 error
	}
	PullBranchStub        func(string, int, bool, bool) error
	pullBranchMutex       sync.RWMutex
	pullBranchArgsForCall []struct {
		arg1 string
		arg2 int
		arg3 bool
		arg4 bool
	}
	pullBranchReturns struct {
		result1 error
	}
	pullBranchReturnsOnCall map[int]struct {
		result1 error
	}
	RebasePrStub        func(string, string, bool) error
	rebasePrMutex       sync.RWMutex
	rebasePrArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 bool
	}
	rebasePrReturns struct {
		result1 error
	}
	rebasePrReturnsOnCall map[int]struct {
		result1 error
	}
	UpdatePRStatusStub        func(string, string, string) error
	updatePRStatusMutex       sync.RWMutex
	updatePRStatusArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	updatePRStatusReturns struct {
		result1 error
	}
	updatePRStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGithubClient) APIEndpoints() (string, string) {
	fake.aPIEndpointsMutex.Lock()
	ret, specificReturn := fake.aPIEndpointsReturnsOnCall[len(fake.aPIEndpointsArgsForCall)]
	fake.aPIEndpointsArgsForCall = append(fake.aPIEndpointsArgsForCall, struct {
	}{})
	stub := fake.APIEndpointsStub
	fakeReturns := fake.aPIEndpointsReturns
	fake.recordInvocation("APIEndpoints", []interface{}{})
	fake.aPIEndpointsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) APIEndpointsCallCount() int {
	fake.aPIEndpointsMutex.RLock()
	defer fake.aPIEndpointsMutex.RUnlock()
	return len(fake.aPIEndpointsArgsForCall)
}

func (fake *FakeGithubClient) APIEndpointsCalls(stub func() (string, string)) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = stub
}

func (fake *FakeGithubClient) APIEndpointsReturns(result1 string, result2 string) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = nil
	fake.aPIEndpointsReturns = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeGithubClient) APIEndpointsReturnsOnCall(i int, result1 string, result2 string) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = nil
	if fake.aPIEndpointsReturnsOnCall == nil {
		fake.aPIEndpointsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
		})
	}
	fake.aPIEndpointsReturnsOnCall[i] = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeGithubClient) AccessToken() string {
	fake.accessTokenMutex.Lock()
	ret, specificReturn := fake.accessTokenReturnsOnCall[len(fake.accessTokenArgsForCall)]
	fake.accessTokenArgsForCall = append(fake.accessTokenArgsForCall, struct {
	}{})
	stub := fake.AccessTokenStub
	fakeReturns := fake.accessTokenReturns
	fake.recordInvocation("AccessToken", []interface{}{})
	fake.accessTokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) AccessTokenCallCount() int {
	fake.accessTokenMutex.RLock()
	defer fake.accessTokenMutex.RUnlock()
	return len(fake.accessTokenArgsForCall)
}

func (fake *FakeGithubClient) AccessTokenCalls(stub func() string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = stub
}

func (fake *FakeGithubClient) AccessTokenReturns(result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	fake.accessTokenReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) AccessTokenReturnsOnCall(i int, result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	if fake.accessTokenReturnsOnCall == nil {
		fake.accessTokenReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.accessTokenReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) CheckoutPr(arg1 string, arg2 string, arg3 bool) error {
	fake.checkoutPrMutex.Lock()
	ret, specificReturn := fake.checkoutPrReturnsOnCall[len(fake.checkoutPrArgsForCall)]
	fake.checkoutPrArgsForCall = append(fake.checkoutPrArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.CheckoutPrStub
	fakeReturns := fake.checkoutPrReturns
	fake.recordInvocation("CheckoutPr", []interface{}{arg1, arg2, arg3})
	fake.checkoutPrMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) CheckoutPrCallCount() int {
	fake.checkoutPrMutex.RLock()
	defer fake.checkoutPrMutex.RUnlock()
	return len(fake.checkoutPrArgsForCall)
}

func (fake *FakeGithubClient) CheckoutPrCalls(stub func(string, string, bool) error) {
	fake.checkoutPrMutex.Lock()
	defer fake.checkoutPrMutex.Unlock()
	fake.CheckoutPrStub = stub
}

func (fake *FakeGithubClient) CheckoutPrArgsForCall(i int) (string, string, bool) {
	fake.checkoutPrMutex.RLock()
	defer fake.checkoutPrMutex.RUnlock()
	argsForCall := fake.checkoutPrArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGithubClient) CheckoutPrReturns(result1 error) {
	fake.checkoutPrMutex.Lock()
	defer fake.checkoutPrMutex.Unlock()
	fake.CheckoutPrStub = nil
	fake.checkoutPrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) CheckoutPrReturnsOnCall(i int, result1 error) {
	fake.checkoutPrMutex.Lock()
	defer fake.checkoutPrMutex.Unlock()
	fake.CheckoutPrStub = nil
	if fake.checkoutPrReturnsOnCall == nil {
		fake.checkoutPrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkoutPrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) FetchPr(arg1 string, arg2 string, arg3 int, arg4 bool, arg5 bool) error {
	fake.fetchPrMutex.Lock()
	ret, specificReturn := fake.fetchPrReturnsOnCall[len(fake.fetchPrArgsForCall)]
	fake.fetchPrArgsForCall = append(fake.fetchPrArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 int
		arg4 bool
		arg5 bool
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.FetchPrStub
	fakeReturns := fake.fetchPrReturns
	fake.recordInvocation("FetchPr", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.fetchPrMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) FetchPrCallCount() int {
	fake.fetchPrMutex.RLock()
	defer fake.fetchPrMutex.RUnlock()
	return len(fake.fetchPrArgsForCall)
}

func (fake *FakeGithubClient) FetchPrCalls(stub func(string, string, int, bool, bool) error) {
	fake.fetchPrMutex.Lock()
	defer fake.fetchPrMutex.Unlock()
	fake.FetchPrStub = stub
}

func (fake *FakeGithubClient) FetchPrArgsForCall(i int) (string, string, int, bool, bool) {
	fake.fetchPrMutex.RLock()
	defer fake.fetchPrMutex.RUnlock()
	argsForCall := fake.fetchPrArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeGithubClient) FetchPrReturns(result1 error) {
	fake.fetchPrMutex.Lock()
	defer fake.fetchPrMutex.Unlock()
	fake.FetchPrStub = nil
	fake.fetchPrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) FetchPrReturnsOnCall(i int, result1 error) {
	fake.fetchPrMutex.Lock()
	defer fake.fetchPrMutex.Unlock()
	fake.FetchPrStub = nil
	if fake.fetchPrReturnsOnCall == nil {
		fake.fetchPrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchPrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) GetPRInfo(arg1 int) (githubresource.PullRequest, error) {
	fake.getPRInfoMutex.Lock()
	ret, specificReturn := fake.getPRInfoReturnsOnCall[len(fake.getPRInfoArgsForCall)]
	fake.getPRInfoArgsForCall = append(fake.getPRInfoArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetPRInfoStub
	fakeReturns := fake.getPRInfoReturns
	fake.recordInvocation("GetPRInfo", []interface{}{arg1})
	fake.getPRInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) GetPRInfoCallCount() int {
	fake.getPRInfoMutex.RLock()
	defer fake.getPRInfoMutex.RUnlock()
	return len(fake.getPRInfoArgsForCall)
}

func (fake *FakeGithubClient) GetPRInfoCalls(stub func(int) (githubresource.PullRequest, error)) {
	fake.getPRInfoMutex.Lock()
	defer fake.getPRInfoMutex.Unlock()
	fake.GetPRInfoStub = stub
}

func (fake *FakeGithubClient) GetPRInfoArgsForCall(i int) int {
	fake.getPRInfoMutex.RLock()
	defer fake.getPRInfoMutex.RUnlock()
	argsForCall := fake.getPRInfoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithubClient) GetPRInfoReturns(result1 githubresource.PullRequest, result2 error) {
	fake.getPRInfoMutex.Lock()
	defer fake.getPRInfoMutex.Unlock()
	fake.GetPRInfoStub = nil
	fake.getPRInfoReturns = struct {
		result1 githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) GetPRInfoReturnsOnCall(i int, result1 githubresource.PullRequest, result2 error) {
	fake.getPRInfoMutex.Lock()
	defer fake.getPRInfoMutex.Unlock()
	fake.GetPRInfoStub = nil
	if fake.getPRInfoReturnsOnCall == nil {
		fake.getPRInfoReturnsOnCall = make(map[int]struct {
			result1 githubresource.PullRequest
			result2 error
		})
	}
	fake.getPRInfoReturnsOnCall[i] = struct {
		result1 githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) HostEndpoint() string {
	fake.hostEndpointMutex.Lock()
	ret, specificReturn := fake.hostEndpointReturnsOnCall[len(fake.hostEndpointArgsForCall)]
	fake.hostEndpointArgsForCall = append(fake.hostEndpointArgsForCall, struct {
	}{})
	stub := fake.HostEndpointStub
	fakeReturns := fake.hostEndpointReturns
	fake.recordInvocation("HostEndpoint", []interface{}{})
	fake.hostEndpointMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) HostEndpointCallCount() int {
	fake.hostEndpointMutex.RLock()
	defer fake.hostEndpointMutex.RUnlock()
	return len(fake.hostEndpointArgsForCall)
}

func (fake *FakeGithubClient) HostEndpointCalls(stub func() string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = stub
}

func (fake *FakeGithubClient) HostEndpointReturns(result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	fake.hostEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) HostEndpointReturnsOnCall(i int, result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	if fake.hostEndpointReturnsOnCall == nil {
		fake.hostEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.hostEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) InitRepo(arg1 string, arg2 string) error {
	fake.initRepoMutex.Lock()
	ret, specificReturn := fake.initRepoReturnsOnCall[len(fake.initRepoArgsForCall)]
	fake.initRepoArgsForCall = append(fake.initRepoArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.InitRepoStub
	fakeReturns := fake.initRepoReturns
	fake.recordInvocation("InitRepo", []interface{}{arg1, arg2})
	fake.initRepoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) InitRepoCallCount() int {
	fake.initRepoMutex.RLock()
	defer fake.initRepoMutex.RUnlock()
	return len(fake.initRepoArgsForCall)
}

func (fake *FakeGithubClient) InitRepoCalls(stub func(string, string) error) {
	fake.initRepoMutex.Lock()
	defer fake.initRepoMutex.Unlock()
	fake.InitRepoStub = stub
}

func (fake *FakeGithubClient) InitRepoArgsForCall(i int) (string, string) {
	fake.initRepoMutex.RLock()
	defer fake.initRepoMutex.RUnlock()
	argsForCall := fake.initRepoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithubClient) InitRepoReturns(result1 error) {
	fake.initRepoMutex.Lock()
	defer fake.initRepoMutex.Unlock()
	fake.InitRepoStub = nil
	fake.initRepoReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) InitRepoReturnsOnCall(i int, result1 error) {
	fake.initRepoMutex.Lock()
	defer fake.initRepoMutex.Unlock()
	fake.InitRepoStub = nil
	if fake.initRepoReturnsOnCall == nil {
		fake.initRepoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.initRepoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) LatestCommitForPR(arg1 int) (string, error) {
	fake.latestCommitForPRMutex.Lock()
	ret, specificReturn := fake.latestCommitForPRReturnsOnCall[len(fake.latestCommitForPRArgsForCall)]
	fake.latestCommitForPRArgsForCall = append(fake.latestCommitForPRArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.LatestCommitForPRStub
	fakeReturns := fake.latestCommitForPRReturns
	fake.recordInvocation("LatestCommitForPR", []interface{}{arg1})
	fake.latestCommitForPRMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) LatestCommitForPRCallCount() int {
	fake.latestCommitForPRMutex.RLock()
	defer fake.latestCommitForPRMutex.RUnlock()
	return len(fake.latestCommitForPRArgsForCall)
}

func (fake *FakeGithubClient) LatestCommitForPRCalls(stub func(int) (string, error)) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = stub
}

func (fake *FakeGithubClient) LatestCommitForPRArgsForCall(i int) int {
	fake.latestCommitForPRMutex.RLock()
	defer fake.latestCommitForPRMutex.RUnlock()
	argsForCall := fake.latestCommitForPRArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithubClient) LatestCommitForPRReturns(result1 string, result2 error) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = nil
	fake.latestCommitForPRReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) LatestCommitForPRReturnsOnCall(i int, result1 string, result2 error) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = nil
	if fake.latestCommitForPRReturnsOnCall == nil {
		fake.latestCommitForPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.latestCommitForPRReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) ListPullRequests(arg1 []githubresource.PullRequestState, arg2 []string) ([]githubresource.PullRequest, error) {
	var arg1Copy []githubresource.PullRequestState
	if arg1 != nil {
		arg1Copy = make([]githubresource.PullRequestState, len(arg1))
		copy(arg1Copy, arg1)
	}
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.listPullRequestsMutex.Lock()
	ret, specificReturn := fake.listPullRequestsReturnsOnCall[len(fake.listPullRequestsArgsForCall)]
	fake.listPullRequestsArgsForCall = append(fake.listPullRequestsArgsForCall, struct {
		arg1 []githubresource.PullRequestState
		arg2 []string
	}{arg1Copy, arg2Copy})
	stub := fake.ListPullRequestsStub
	fakeReturns := fake.listPullRequestsReturns
	fake.recordInvocation("ListPullRequests", []interface{}{arg1Copy, arg2Copy})
	fake.listPullRequestsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) ListPullRequestsCallCount() int {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	return len(fake.listPullRequestsArgsForCall)
}

func (fake *FakeGithubClient) ListPullRequestsCalls(stub func([]githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = stub
}

func (fake *FakeGithubClient) ListPullRequestsArgsForCall(i int) ([]githubresource.PullRequestState, []string) {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	argsForCall := fake.listPullRequestsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithubClient) ListPullRequestsReturns(result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	fake.listPullRequestsReturns = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) ListPullRequestsReturnsOnCall(i int, result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	if fake.listPullRequestsReturnsOnCall == nil {
		fake.listPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []githubresource.PullRequest
			result2 error
		})
	}
	fake.listPullRequestsReturnsOnCall[i] = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) MergePr(arg1 string, arg2 bool) error {
	fake.mergePrMutex.Lock()
	ret, specificReturn := fake.mergePrReturnsOnCall[len(fake.mergePrArgsForCall)]
	fake.mergePrArgsForCall = append(fake.mergePrArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.MergePrStub
	fakeReturns := fake.mergePrReturns
	fake.recordInvocation("MergePr", []interface{}{arg1, arg2})
	fake.mergePrMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) MergePrCallCount() int {
	fake.mergePrMutex.RLock()
	defer fake.mergePrMutex.RUnlock()
	return len(fake.mergePrArgsForCall)
}

func (fake *FakeGithubClient) MergePrCalls(stub func(string, bool) error) {
	fake.mergePrMutex.Lock()
	defer fake.mergePrMutex.Unlock()
	fake.MergePrStub = stub
}

func (fake *FakeGithubClient) MergePrArgsForCall(i int) (string, bool) {
	fake.mergePrMutex.RLock()
	defer fake.mergePrMutex.RUnlock()
	argsForCall := fake.mergePrArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithubClient) MergePrReturns(result1 error) {
	fake.mergePrMutex.Lock()
	defer fake.mergePrMutex.Unlock()
	fake.MergePrStub = nil
	fake.mergePrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) MergePrReturnsOnCall(i int, result1 error) {
	fake.mergePrMutex.Lock()
	defer fake.mergePrMutex.Unlock()
	fake.MergePrStub = nil
	if fake.mergePrReturnsOnCall == nil {
		fake.mergePrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mergePrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) PullBranch(arg1 string, arg2 int, arg3 bool, arg4 bool) error {
	fake.pullBranchMutex.Lock()
	ret, specificReturn := fake.pullBranchReturnsOnCall[len(fake.pullBranchArgsForCall)]
	fake.pullBranchArgsForCall = append(fake.pullBranchArgsForCall, struct {
		arg1 string
		arg2 int
		arg3 bool
		arg4 bool
	}{arg1, arg2, arg3, arg4})
	stub := fake.PullBranchStub
	fakeReturns := fake.pullBranchReturns
	fake.recordInvocation("PullBranch", []interface{}{arg1, arg2, arg3, arg4})
	fake.pullBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) PullBranchCallCount() int {
	fake.pullBranchMutex.RLock()
	defer fake.pullBranchMutex.RUnlock()
	return len(fake.pullBranchArgsForCall)
}

func (fake *FakeGithubClient) PullBranchCalls(stub func(string, int, bool, bool) error) {
	fake.pullBranchMutex.Lock()
	defer fake.pullBranchMutex.Unlock()
	fake.PullBranchStub = stub
}

func (fake *FakeGithubClient) PullBranchArgsForCall(i int) (string, int, bool, bool) {
	fake.pullBranchMutex.RLock()
	defer fake.pullBranchMutex.RUnlock()
	argsForCall := fake.pullBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGithubClient) PullBranchReturns(result1 error) {
	fake.pullBranchMutex.Lock()
	defer fake.pullBranchMutex.Unlock()
	fake.PullBranchStub = nil
	fake.pullBranchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) PullBranchReturnsOnCall(i int, result1 error) {
	fake.pullBranchMutex.Lock()
	defer fake.pullBranchMutex.Unlock()
	fake.PullBranchStub = nil
	if fake.pullBranchReturnsOnCall == nil {
		fake.pullBranchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullBranchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) RebasePr(arg1 string, arg2 string, arg3 bool) error {
	fake.rebasePrMutex.Lock()
	ret, specificReturn := fake.rebasePrReturnsOnCall[len(fake.rebasePrArgsForCall)]
	fake.rebasePrArgsForCall = append(fake.rebasePrArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.RebasePrStub
	fakeReturns := fake.rebasePrReturns
	fake.recordInvocation("RebasePr", []interface{}{arg1, arg2, arg3})
	fake.rebasePrMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) RebasePrCallCount() int {
	fake.rebasePrMutex.RLock()
	defer fake.rebasePrMutex.RUnlock()
	return len(fake.rebasePrArgsForCall)
}

func (fake *FakeGithubClient) RebasePrCalls(stub func(string, string, bool) error) {
	fake.rebasePrMutex.Lock()
	defer fake.rebasePrMutex.Unlock()
	fake.RebasePrStub = stub
}

func (fake *FakeGithubClient) RebasePrArgsForCall(i int) (string, string, bool) {
	fake.rebasePrMutex.RLock()
	defer fake.rebasePrMutex.RUnlock()
	argsForCall := fake.rebasePrArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGithubClient) RebasePrReturns(result1 error) {
	fake.rebasePrMutex.Lock()
	defer fake.rebasePrMutex.Unlock()
	fake.RebasePrStub = nil
	fake.rebasePrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) RebasePrReturnsOnCall(i int, result1 error) {
	fake.rebasePrMutex.Lock()
	defer fake.rebasePrMutex.Unlock()
	fake.RebasePrStub = nil
	if fake.rebasePrReturnsOnCall == nil {
		fake.rebasePrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rebasePrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) UpdatePRStatus(arg1 string, arg2 string, arg3 string) error {
	fake.updatePRStatusMutex.Lock()
	ret, specificReturn := fake.updatePRStatusReturnsOnCall[len(fake.updatePRStatusArgsForCall)]
	fake.updatePRStatusArgsForCall = append(fake.updatePRStatusArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UpdatePRStatusStub
	fakeReturns := fake.updatePRStatusReturns
	fake.recordInvocation("UpdatePRStatus", []interface{}{arg1, arg2, arg3})
	fake.updatePRStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) UpdatePRStatusCallCount() int {
	fake.updatePRStatusMutex.RLock()
	defer fake.updatePRStatusMutex.RUnlock()
	return len(fake.updatePRStatusArgsForCall)
}

func (fake *FakeGithubClient) UpdatePRStatusCalls(stub func(string, string, string) error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = stub
}

func (fake *FakeGithubClient) UpdatePRStatusArgsForCall(i int) (string, string, string) {
	fake.updatePRStatusMutex.RLock()
	defer fake.updatePRStatusMutex.RUnlock()
	argsForCall := fake.updatePRStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGithubClient) UpdatePRStatusReturns(result1 error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = nil
	fake.updatePRStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) UpdatePRStatusReturnsOnCall(i int, result1 error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = nil
	if fake.updatePRStatusReturnsOnCall == nil {
		fake.updatePRStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updatePRStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGithubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubresource.GithubClient = new(FakeGithubClient)
