// Code generated by counterfeiter. DO NOT EDIT.
package githubresourcefakes

import (
	"sync"

	githubresource "github.com/PixelAirIO/github-resource"
)

type FakeGithubClient struct {
	APIEndpointsStub        func() (string, string)
	aPIEndpointsMutex       sync.RWMutex
	aPIEndpointsArgsForCall []struct {
	}
	aPIEndpointsReturns struct {
		result1 string
		result2 string
	}
	aPIEndpointsReturnsOnCall map[int]struct {
		result1 string
		result2 string
	}
	AccessTokenStub        func() string
	accessTokenMutex       sync.RWMutex
	accessTokenArgsForCall []struct {
	}
	accessTokenReturns struct {
		result1 string
	}
	accessTokenReturnsOnCall map[int]struct {
		result1 string
	}
	HostEndpointStub        func() string
	hostEndpointMutex       sync.RWMutex
	hostEndpointArgsForCall []struct {
	}
	hostEndpointReturns struct {
		result1 string
	}
	hostEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	LatestCommitForPRStub        func(int) (string, error)
	latestCommitForPRMutex       sync.RWMutex
	latestCommitForPRArgsForCall []struct {
		arg1 int
	}
	latestCommitForPRReturns struct {
		result1 string
		result2 error
	}
	latestCommitForPRReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ListPullRequestsStub        func([]githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)
	listPullRequestsMutex       sync.RWMutex
	listPullRequestsArgsForCall []struct {
		arg1 []githubresource.PullRequestState
		arg2 []string
	}
	listPullRequestsReturns struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	listPullRequestsReturnsOnCall map[int]struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	UpdatePRStatusStub        func(string, string, string) error
	updatePRStatusMutex       sync.RWMutex
	updatePRStatusArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	updatePRStatusReturns struct {
		result1 error
	}
	updatePRStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGithubClient) APIEndpoints() (string, string) {
	fake.aPIEndpointsMutex.Lock()
	ret, specificReturn := fake.aPIEndpointsReturnsOnCall[len(fake.aPIEndpointsArgsForCall)]
	fake.aPIEndpointsArgsForCall = append(fake.aPIEndpointsArgsForCall, struct {
	}{})
	stub := fake.APIEndpointsStub
	fakeReturns := fake.aPIEndpointsReturns
	fake.recordInvocation("APIEndpoints", []interface{}{})
	fake.aPIEndpointsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) APIEndpointsCallCount() int {
	fake.aPIEndpointsMutex.RLock()
	defer fake.aPIEndpointsMutex.RUnlock()
	return len(fake.aPIEndpointsArgsForCall)
}

func (fake *FakeGithubClient) APIEndpointsCalls(stub func() (string, string)) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = stub
}

func (fake *FakeGithubClient) APIEndpointsReturns(result1 string, result2 string) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = nil
	fake.aPIEndpointsReturns = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeGithubClient) APIEndpointsReturnsOnCall(i int, result1 string, result2 string) {
	fake.aPIEndpointsMutex.Lock()
	defer fake.aPIEndpointsMutex.Unlock()
	fake.APIEndpointsStub = nil
	if fake.aPIEndpointsReturnsOnCall == nil {
		fake.aPIEndpointsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
		})
	}
	fake.aPIEndpointsReturnsOnCall[i] = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeGithubClient) AccessToken() string {
	fake.accessTokenMutex.Lock()
	ret, specificReturn := fake.accessTokenReturnsOnCall[len(fake.accessTokenArgsForCall)]
	fake.accessTokenArgsForCall = append(fake.accessTokenArgsForCall, struct {
	}{})
	stub := fake.AccessTokenStub
	fakeReturns := fake.accessTokenReturns
	fake.recordInvocation("AccessToken", []interface{}{})
	fake.accessTokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) AccessTokenCallCount() int {
	fake.accessTokenMutex.RLock()
	defer fake.accessTokenMutex.RUnlock()
	return len(fake.accessTokenArgsForCall)
}

func (fake *FakeGithubClient) AccessTokenCalls(stub func() string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = stub
}

func (fake *FakeGithubClient) AccessTokenReturns(result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	fake.accessTokenReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) AccessTokenReturnsOnCall(i int, result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	if fake.accessTokenReturnsOnCall == nil {
		fake.accessTokenReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.accessTokenReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) HostEndpoint() string {
	fake.hostEndpointMutex.Lock()
	ret, specificReturn := fake.hostEndpointReturnsOnCall[len(fake.hostEndpointArgsForCall)]
	fake.hostEndpointArgsForCall = append(fake.hostEndpointArgsForCall, struct {
	}{})
	stub := fake.HostEndpointStub
	fakeReturns := fake.hostEndpointReturns
	fake.recordInvocation("HostEndpoint", []interface{}{})
	fake.hostEndpointMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) HostEndpointCallCount() int {
	fake.hostEndpointMutex.RLock()
	defer fake.hostEndpointMutex.RUnlock()
	return len(fake.hostEndpointArgsForCall)
}

func (fake *FakeGithubClient) HostEndpointCalls(stub func() string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = stub
}

func (fake *FakeGithubClient) HostEndpointReturns(result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	fake.hostEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) HostEndpointReturnsOnCall(i int, result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	if fake.hostEndpointReturnsOnCall == nil {
		fake.hostEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.hostEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) LatestCommitForPR(arg1 int) (string, error) {
	fake.latestCommitForPRMutex.Lock()
	ret, specificReturn := fake.latestCommitForPRReturnsOnCall[len(fake.latestCommitForPRArgsForCall)]
	fake.latestCommitForPRArgsForCall = append(fake.latestCommitForPRArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.LatestCommitForPRStub
	fakeReturns := fake.latestCommitForPRReturns
	fake.recordInvocation("LatestCommitForPR", []interface{}{arg1})
	fake.latestCommitForPRMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) LatestCommitForPRCallCount() int {
	fake.latestCommitForPRMutex.RLock()
	defer fake.latestCommitForPRMutex.RUnlock()
	return len(fake.latestCommitForPRArgsForCall)
}

func (fake *FakeGithubClient) LatestCommitForPRCalls(stub func(int) (string, error)) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = stub
}

func (fake *FakeGithubClient) LatestCommitForPRArgsForCall(i int) int {
	fake.latestCommitForPRMutex.RLock()
	defer fake.latestCommitForPRMutex.RUnlock()
	argsForCall := fake.latestCommitForPRArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithubClient) LatestCommitForPRReturns(result1 string, result2 error) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = nil
	fake.latestCommitForPRReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) LatestCommitForPRReturnsOnCall(i int, result1 string, result2 error) {
	fake.latestCommitForPRMutex.Lock()
	defer fake.latestCommitForPRMutex.Unlock()
	fake.LatestCommitForPRStub = nil
	if fake.latestCommitForPRReturnsOnCall == nil {
		fake.latestCommitForPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.latestCommitForPRReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) ListPullRequests(arg1 []githubresource.PullRequestState, arg2 []string) ([]githubresource.PullRequest, error) {
	var arg1Copy []githubresource.PullRequestState
	if arg1 != nil {
		arg1Copy = make([]githubresource.PullRequestState, len(arg1))
		copy(arg1Copy, arg1)
	}
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.listPullRequestsMutex.Lock()
	ret, specificReturn := fake.listPullRequestsReturnsOnCall[len(fake.listPullRequestsArgsForCall)]
	fake.listPullRequestsArgsForCall = append(fake.listPullRequestsArgsForCall, struct {
		arg1 []githubresource.PullRequestState
		arg2 []string
	}{arg1Copy, arg2Copy})
	stub := fake.ListPullRequestsStub
	fakeReturns := fake.listPullRequestsReturns
	fake.recordInvocation("ListPullRequests", []interface{}{arg1Copy, arg2Copy})
	fake.listPullRequestsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) ListPullRequestsCallCount() int {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	return len(fake.listPullRequestsArgsForCall)
}

func (fake *FakeGithubClient) ListPullRequestsCalls(stub func([]githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = stub
}

func (fake *FakeGithubClient) ListPullRequestsArgsForCall(i int) ([]githubresource.PullRequestState, []string) {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	argsForCall := fake.listPullRequestsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithubClient) ListPullRequestsReturns(result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	fake.listPullRequestsReturns = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) ListPullRequestsReturnsOnCall(i int, result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	if fake.listPullRequestsReturnsOnCall == nil {
		fake.listPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []githubresource.PullRequest
			result2 error
		})
	}
	fake.listPullRequestsReturnsOnCall[i] = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) UpdatePRStatus(arg1 string, arg2 string, arg3 string) error {
	fake.updatePRStatusMutex.Lock()
	ret, specificReturn := fake.updatePRStatusReturnsOnCall[len(fake.updatePRStatusArgsForCall)]
	fake.updatePRStatusArgsForCall = append(fake.updatePRStatusArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UpdatePRStatusStub
	fakeReturns := fake.updatePRStatusReturns
	fake.recordInvocation("UpdatePRStatus", []interface{}{arg1, arg2, arg3})
	fake.updatePRStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) UpdatePRStatusCallCount() int {
	fake.updatePRStatusMutex.RLock()
	defer fake.updatePRStatusMutex.RUnlock()
	return len(fake.updatePRStatusArgsForCall)
}

func (fake *FakeGithubClient) UpdatePRStatusCalls(stub func(string, string, string) error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = stub
}

func (fake *FakeGithubClient) UpdatePRStatusArgsForCall(i int) (string, string, string) {
	fake.updatePRStatusMutex.RLock()
	defer fake.updatePRStatusMutex.RUnlock()
	argsForCall := fake.updatePRStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGithubClient) UpdatePRStatusReturns(result1 error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = nil
	fake.updatePRStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) UpdatePRStatusReturnsOnCall(i int, result1 error) {
	fake.updatePRStatusMutex.Lock()
	defer fake.updatePRStatusMutex.Unlock()
	fake.UpdatePRStatusStub = nil
	if fake.updatePRStatusReturnsOnCall == nil {
		fake.updatePRStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updatePRStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGithubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubresource.GithubClient = new(FakeGithubClient)
