// Code generated by counterfeiter. DO NOT EDIT.
package githubresourcefakes

import (
	"sync"

	githubresource "github.com/PixelAirIO/github-resource"
)

type FakeGithubClient struct {
	APIEndpointStub        func() string
	aPIEndpointMutex       sync.RWMutex
	aPIEndpointArgsForCall []struct {
	}
	aPIEndpointReturns struct {
		result1 string
	}
	aPIEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	AccessTokenStub        func() string
	accessTokenMutex       sync.RWMutex
	accessTokenArgsForCall []struct {
	}
	accessTokenReturns struct {
		result1 string
	}
	accessTokenReturnsOnCall map[int]struct {
		result1 string
	}
	HostEndpointStub        func() string
	hostEndpointMutex       sync.RWMutex
	hostEndpointArgsForCall []struct {
	}
	hostEndpointReturns struct {
		result1 string
	}
	hostEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	ListPullRequestsStub        func(string, string, []githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)
	listPullRequestsMutex       sync.RWMutex
	listPullRequestsArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 []githubresource.PullRequestState
		arg4 []string
	}
	listPullRequestsReturns struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	listPullRequestsReturnsOnCall map[int]struct {
		result1 []githubresource.PullRequest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGithubClient) APIEndpoint() string {
	fake.aPIEndpointMutex.Lock()
	ret, specificReturn := fake.aPIEndpointReturnsOnCall[len(fake.aPIEndpointArgsForCall)]
	fake.aPIEndpointArgsForCall = append(fake.aPIEndpointArgsForCall, struct {
	}{})
	stub := fake.APIEndpointStub
	fakeReturns := fake.aPIEndpointReturns
	fake.recordInvocation("APIEndpoint", []interface{}{})
	fake.aPIEndpointMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) APIEndpointCallCount() int {
	fake.aPIEndpointMutex.RLock()
	defer fake.aPIEndpointMutex.RUnlock()
	return len(fake.aPIEndpointArgsForCall)
}

func (fake *FakeGithubClient) APIEndpointCalls(stub func() string) {
	fake.aPIEndpointMutex.Lock()
	defer fake.aPIEndpointMutex.Unlock()
	fake.APIEndpointStub = stub
}

func (fake *FakeGithubClient) APIEndpointReturns(result1 string) {
	fake.aPIEndpointMutex.Lock()
	defer fake.aPIEndpointMutex.Unlock()
	fake.APIEndpointStub = nil
	fake.aPIEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) APIEndpointReturnsOnCall(i int, result1 string) {
	fake.aPIEndpointMutex.Lock()
	defer fake.aPIEndpointMutex.Unlock()
	fake.APIEndpointStub = nil
	if fake.aPIEndpointReturnsOnCall == nil {
		fake.aPIEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.aPIEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) AccessToken() string {
	fake.accessTokenMutex.Lock()
	ret, specificReturn := fake.accessTokenReturnsOnCall[len(fake.accessTokenArgsForCall)]
	fake.accessTokenArgsForCall = append(fake.accessTokenArgsForCall, struct {
	}{})
	stub := fake.AccessTokenStub
	fakeReturns := fake.accessTokenReturns
	fake.recordInvocation("AccessToken", []interface{}{})
	fake.accessTokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) AccessTokenCallCount() int {
	fake.accessTokenMutex.RLock()
	defer fake.accessTokenMutex.RUnlock()
	return len(fake.accessTokenArgsForCall)
}

func (fake *FakeGithubClient) AccessTokenCalls(stub func() string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = stub
}

func (fake *FakeGithubClient) AccessTokenReturns(result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	fake.accessTokenReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) AccessTokenReturnsOnCall(i int, result1 string) {
	fake.accessTokenMutex.Lock()
	defer fake.accessTokenMutex.Unlock()
	fake.AccessTokenStub = nil
	if fake.accessTokenReturnsOnCall == nil {
		fake.accessTokenReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.accessTokenReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) HostEndpoint() string {
	fake.hostEndpointMutex.Lock()
	ret, specificReturn := fake.hostEndpointReturnsOnCall[len(fake.hostEndpointArgsForCall)]
	fake.hostEndpointArgsForCall = append(fake.hostEndpointArgsForCall, struct {
	}{})
	stub := fake.HostEndpointStub
	fakeReturns := fake.hostEndpointReturns
	fake.recordInvocation("HostEndpoint", []interface{}{})
	fake.hostEndpointMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGithubClient) HostEndpointCallCount() int {
	fake.hostEndpointMutex.RLock()
	defer fake.hostEndpointMutex.RUnlock()
	return len(fake.hostEndpointArgsForCall)
}

func (fake *FakeGithubClient) HostEndpointCalls(stub func() string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = stub
}

func (fake *FakeGithubClient) HostEndpointReturns(result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	fake.hostEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) HostEndpointReturnsOnCall(i int, result1 string) {
	fake.hostEndpointMutex.Lock()
	defer fake.hostEndpointMutex.Unlock()
	fake.HostEndpointStub = nil
	if fake.hostEndpointReturnsOnCall == nil {
		fake.hostEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.hostEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGithubClient) ListPullRequests(arg1 string, arg2 string, arg3 []githubresource.PullRequestState, arg4 []string) ([]githubresource.PullRequest, error) {
	var arg3Copy []githubresource.PullRequestState
	if arg3 != nil {
		arg3Copy = make([]githubresource.PullRequestState, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.listPullRequestsMutex.Lock()
	ret, specificReturn := fake.listPullRequestsReturnsOnCall[len(fake.listPullRequestsArgsForCall)]
	fake.listPullRequestsArgsForCall = append(fake.listPullRequestsArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 []githubresource.PullRequestState
		arg4 []string
	}{arg1, arg2, arg3Copy, arg4Copy})
	stub := fake.ListPullRequestsStub
	fakeReturns := fake.listPullRequestsReturns
	fake.recordInvocation("ListPullRequests", []interface{}{arg1, arg2, arg3Copy, arg4Copy})
	fake.listPullRequestsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithubClient) ListPullRequestsCallCount() int {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	return len(fake.listPullRequestsArgsForCall)
}

func (fake *FakeGithubClient) ListPullRequestsCalls(stub func(string, string, []githubresource.PullRequestState, []string) ([]githubresource.PullRequest, error)) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = stub
}

func (fake *FakeGithubClient) ListPullRequestsArgsForCall(i int) (string, string, []githubresource.PullRequestState, []string) {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	argsForCall := fake.listPullRequestsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGithubClient) ListPullRequestsReturns(result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	fake.listPullRequestsReturns = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) ListPullRequestsReturnsOnCall(i int, result1 []githubresource.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	if fake.listPullRequestsReturnsOnCall == nil {
		fake.listPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []githubresource.PullRequest
			result2 error
		})
	}
	fake.listPullRequestsReturnsOnCall[i] = struct {
		result1 []githubresource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGithubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubresource.GithubClient = new(FakeGithubClient)
